version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "ng-packagr"
          - "typescript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
